Background color for clients
streaver/teams-builder pull request #29
Opened 2023-03-09 19:31 UTC by npraderi

2023-03-09 20:41 UTC, juanlarrambebere requested changes
I know this review might be rough since I left you a bunch of comments but don't take it wrong, I'm trying to help you improve.

If you don't understand some of of the things I mentioned, please feel free to reach me out and I can help you with the refactor.

2023-03-09 20:41 UTC, juanlarrambebere commented on src/components/ColorPicker.tsx
> +export const ColorPicker = (props: Props) => {
Hmmm this component feels pretty unnecessary, don't you think? It receives 2 props and renders something that uses those 2 props, it has 0 extra logic. Though the name looks better that's true..

2023-03-09 20:41 UTC, juanlarrambebere commented on src/state/recoil/selectors/clientsSelectorFamily.ts
> +});
This shouldn't be a `selectorFamily`, it should be just a `selector`. You don't need a key.

2023-03-09 20:41 UTC, juanlarrambebere commented on src/components/DropDown.tsx
> +}
This utility is intended to remove null/undefined values from the string. You don't need this, tailwind already does it for you. Also, in your code below, you never set a class to null or undefined.

2023-03-09 20:41 UTC, juanlarrambebere commented on src/components/DropDown.tsx
> +  const [selected, setSelected] = useState(clients[0]);
Clients might be empty array. If that's the case, this will 💥. You might want to use the `Optional Chaining` operator to safely read the first position or null if the array is empty.

`clients?.[0]`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2023-03-09 20:41 UTC, juanlarrambebere commented on src/components/DropDown.tsx
> +export const DropDown = ({ setClient, setClientColor }: Props) => {
The name of this component tells me you wanted to create something generic, that could be used for another use case. On the other hand, the props mention clients, therefore this is not a generic Dropdown, is more like a ClientsDropdown or something like that.

Also, currently, the dropdown knows how to get all the options from the global state (it reads the clients) but it doesn't know how to update the selected client, it's the parent the one that's updating the state. That's weird, the component that knows how to get all the options should be the same that updates the selected option, either the parent or the child but not half and half.

2023-03-09 20:41 UTC, juanlarrambebere commented on src/components/ClientColorMenu.tsx
> +  );
I think we should slightly refactor this code, here's how I'd do it:
1. Read the clients from the selector here.
1. Use a local state to store the selected client id, initially it's null.
2. Refactor the Dropdown component to make it generic. That means it should receive two props:
- options: An array with all the options (type Option[] where Option can be something that has an id and a label {id:number | label: string} or something like that)
- onSelect: A function that receives an option. (type (option: Option) => void)
3.  Render the new Dropdown like <Dropdown options={clients} onSelect={handleClientSelected} />
4. Have a ClientColorPicker, that receives a clientId and internally know how to read & update the client's color. That means, it reads the client's atom and updates its color whenever the user picks a new color. Also, I'd disable or hide the color picker if there's no client selected.

2023-03-09 20:41 UTC, juanlarrambebere commented on src/components/team-box/DraggableTeamBox.tsx
> +  const teamColor = useRecoilValue(teamColorSelectorFamily(team.clientId!));
The bang operator (!) here is not right. The team might not have a clientId, so telling typescript it won't be null is not right.

You can either modify the selector so the teamId can be null or use an utility from recoil called constSelector, like this:

`const teamColor = useRecoilValue(team.clientId !== null ? teamColorSelectorFamily(team.clientId) : constSelector(null))`

That way, you only read your selector with a valid clientId otherwise you read a constant selector that always returns null or whatever you want.

2023-03-10 17:18 UTC, npraderi commented on src/state/recoil/selectors/teamColorSelectorFamily.ts
> +export const teamColorSelectorFamily = selectorFamily<
Yes! totally agree!

2023-03-10 17:23 UTC, npraderi commented on src/providers/RecoilProvider.tsx
> +  const [clients, setClients] = useState<Client[] | null>(null);
But what if I don't have clients, I should be able to render the teams, right? Or the idea is having an empty array avoiding null values?

2023-03-10 17:24 UTC, npraderi commented on src/components/ColorPicker.tsx
> +export const ColorPicker = (props: Props) => {
Do you mean that it should be in the parent component?

2023-03-10 17:30 UTC, npraderi commented on src/state/recoil/selectors/clientsSelectorFamily.ts
> +});
`_A selectorFamily is a powerful pattern that is similar to a selector, but allows you to pass parameters to the get and set callbacks of a selector. The selectorFamily() utility returns a function which can be called with user-defined parameters and returns a selector. Each unique parameter value will return the same memoized selector instance._`

In this case, I don't need to pass parameters, and the result value is not a selector to make callbacks, it's just the values I need, right?

2023-03-10 17:35 UTC, npraderi commented on src/components/DropDown.tsx
> +  const [selected, setSelected] = useState(clients[0]);
Great!

2023-03-10 17:36 UTC, npraderi commented on src/components/team-box/DraggableTeamBox.tsx
> +  const teamColor = useRecoilValue(teamColorSelectorFamily(team.clientId!));
Excelent

2023-03-10 17:36 UTC, juanlarrambebere approved these changes

2023-03-10 17:36 UTC, juanlarrambebere commented on src/providers/RecoilProvider.tsx
> +  const [clients, setClients] = useState<Client[] | null>(null);
This component mounts a `RecoilRoot` that, when mounted, initializes all recoil atoms. We need to make sure that the RecoilRoot is not mounted until all data (members, clients and team team members) is available.

We decided that null means "data wasn't loaded yet". As you pointed, this forces us to have at least an empty list in the local storage, otherwise it won't work, but I'm ok with that decision for now. Are you?

2023-03-10 17:38 UTC, npraderi commented on src/providers/RecoilProvider.tsx
> +  const [clients, setClients] = useState<Client[] | null>(null);
Sure!

2023-03-10 17:51 UTC, merged